[package]
name = "vault-stateless-poc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
hmac = "0.11.0"
clipboard = "0.5.0"
regex = "1"